### PR TITLE
fix sort when loop end

### LINKED ISSUE #3: sort bug
```js
const list = [
  'a00000',
  'a0b',
  'a1b',
]

// expect:
// [ 'a00000', 'a0b', 'a1b' ]

// real:
// [ 'a0b', 'a00000', 'a1b' ]
```

### PR DESCRIPTION
**Pull request by LeeHao92**
fix #3

### CODE REVIEW

File: natural-compare.js [hunk 1]
```diff
@@ -77,6 +77,14 @@ function naturalCompare(a, b) {
     ++bIndex;
   }
 
+  if (aIndex >= lengthA && bIndex < lengthB && a.length >= b.length) {
+    return -1;
+  }
+
+  if (bIndex >= lengthB && aIndex < lengthA && b.length >= a.length) {
```
Comment (nwoltman) [inline natural-compare.js]: Instead of `a.length` and `b.length`, please use `lengthA` and `lengthB`.

Comment (LeeHao92) [reply natural-compare.js]: ok
